name: mindbox_ios
description: The implementation of 'mindbox' plugin for the iOS platform.
version: 2.13.4
homepage: https://mindbox.cloud/
repository: https://github.com/mindbox-cloud/flutter-sdk/tree/master/mindbox_ios

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

flutter:
  plugin:
    implements: mindbox
    platforms:
      ios:
        pluginClass: MindboxIosPlugin

dependencies:
  flutter:
    sdk: flutter
  mindbox_platform_interface: ^2.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

analyzer:
  exclude: ['**_test.dart'] 