name: mindbox_ios
description: The implementation of 'mindbox' plugin for the iOS platform.
version: 1.0.0
homepage: https://mindbox.cloud/
repository: https://github.com/mindbox-moscow/flutter-sdk/tree/master/mindbox_ios
#TODO remove before release
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

flutter:
  plugin:
    implements: mindbox
    platforms:
      ios:
        pluginClass: MindboxIosPlugin

dependencies:
  flutter:
    sdk: flutter
  mindbox_platform_interface:
    path: ../mindbox_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
