name: mindbox_android
description: The implementation of 'mindbox' plugin for the Android platform.
version: 2.8.1
homepage: https://mindbox.cloud/
repository: https://github.com/mindbox-cloud/flutter-sdk/tree/master/mindbox_android

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

flutter:
  plugin:
    implements: mindbox
    platforms:
      android:
        package: cloud.mindbox.mindbox_android
        pluginClass: MindboxAndroidPlugin

dependencies:
  flutter:
    sdk: flutter
  mindbox_platform_interface: ^2.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

analyzer:
  exclude: ['**_test.dart']
