name: mindbox_android
description: An implementation of 'mindbox' plugin for the Android platform.
version: 0.1.0
homepage: https://mindbox.cloud/
repository: https://github.com/mindbox-moscow/flutter-sdk/tree/master/mindbox_android

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

flutter:
  plugin:
    implements: mindbox
    platforms:
      android:
        package: cloud.mindbox.mindbox_android
        pluginClass: MindboxAndroidPlugin

dependencies:
  flutter:
    sdk: flutter
  mindbox_platform_interface:
    path: ../mindbox_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4