name: mindbox
description: Flutter Mindbox SDK. Plugin wrapper over of Mindbox iOS/Android SDK.
version: 2.1.2
homepage: https://mindbox.cloud/
repository: https://github.com/mindbox-moscow/flutter-sdk/tree/master/mindbox

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: mindbox_android
      ios:
        default_package: mindbox_ios

dependencies:
  flutter:
    sdk: flutter
  mindbox_android: ^2.1.2
  mindbox_ios: ^2.1.1
  mindbox_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4