name: mindbox
description: Flutter Mindbox SDK. Plugin wrapper over of Mindbox iOS/Android SDK.
version: 2.5.0-rc
homepage: https://mindbox.cloud/
repository: https://github.com/mindbox-cloud/flutter-sdk/tree/master/mindbox
documentation: https://developers.mindbox.ru/docs/flutter-sdk-integration

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

flutter:
  plugin:
    platforms:
      android:
        default_package: mindbox_android
      ios:
        default_package: mindbox_ios

dependencies:
  flutter:
    sdk: flutter
  mindbox_android: ^2.5.0-rc
  mindbox_ios: ^2.5.0-rc
  mindbox_platform_interface: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1